name: Build SlideSCI

on:
  push:
    branches: [ main ]   # 如果你的默认分支是 master 就改成 master
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore SlideSCI.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # ★ 关键：在 CI 里直接改 csproj，关闭所有签名相关设置，去掉 pfx 引用
      - name: Disable signing in csproj (CI only)
        shell: pwsh
        run: |
          $p = "SlideSCI/SlideSCI.csproj"
          Write-Host "Patching $p to disable signing in CI..."
          $c = Get-Content $p -Raw
          $c = $c -replace '<SignAssembly>true</SignAssembly>','<SignAssembly>false</SignAssembly>'
          $c = $c -replace '<SignManifests>true</SignManifests>','<SignManifests>false</SignManifests>'
          $c = $c -replace '<AssemblyOriginatorKeyFile>.*?</AssemblyOriginatorKeyFile>',''
          $c = $c -replace '<ManifestCertificateThumbprint>.*?</ManifestCertificateThumbprint>',''
          $c = $c -replace '<ManifestKeyFile>.*?</ManifestKeyFile>',''
          Set-Content $p $c

      # ★ 只编译项目（不是发布），并再次用命令行参数兜底关闭签名/清单
      - name: Build Release
        run: msbuild SlideSCI/SlideSCI.csproj /t:Rebuild /p:Configuration=Release /p:SignAssembly=false /p:SignManifests=false /p:GenerateManifests=false /m

      - name: Package artifacts
        shell: pwsh
        run: |
          $out = "artifacts"
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          Copy-Item -Recurse -Force "SlideSCI\bin\Release\*" $out
          Compress-Archive -Path $out\* -DestinationPath "SlideSCI_Release.zip" -Force

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SlideSCI_Release
          path: |
            artifacts/**
            SlideSCI_Release.zip
