name: Build SlideSCI

on:
  push:
    branches: [ main ]   # 如果默认分支是 master 就改成 master
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore SlideSCI.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 关键：用 Singleline (?s) 跨行替换，并明确 UTF8 写回
      - name: Disable signing in csproj (CI only)
        shell: pwsh
        run: |
          $p = "SlideSCI/SlideSCI.csproj"
          Write-Host "Patching $p to disable signing in CI..."
          $c = Get-Content $p -Raw
          $c = $c -replace '(?s)<SignAssembly>\s*true\s*</SignAssembly>','<SignAssembly>false</SignAssembly>'
          $c = $c -replace '(?s)<SignManifests>\s*true\s*</SignManifests>','<SignManifests>false</SignManifests>'
          $c = $c -replace '(?s)<AssemblyOriginatorKeyFile>.*?</AssemblyOriginatorKeyFile>',''
          $c = $c -replace '(?s)<ManifestCertificateThumbprint>.*?</ManifestCertificateThumbprint>',''
          $c = $c -replace '(?s)<ManifestKeyFile>.*?</ManifestKeyFile>',''
          Set-Content -Path $p -Value $c -Encoding utf8

      # 打印关键片段确认已经关签名
      - name: Show signing flags after patch
        shell: pwsh
        run: |
          $p = "SlideSCI/SlideSCI.csproj"
          Write-Host "=== Snippet ==="
          Select-String -Path $p -Pattern 'SignAssembly|SignManifests|AssemblyOriginatorKeyFile|ManifestKeyFile|ManifestCertificateThumbprint' -Context 0,1 | ForEach-Object { $_.Line }

      # 再兜底一次：命令行参数关闭所有签名/清单
      - name: Build Release
        run: msbuild SlideSCI/SlideSCI.csproj /t:Rebuild /p:Configuration=Release /p:SignAssembly=false /p:SignManifests=false /p:GenerateManifests=false /m

      - name: Package artifacts
        shell: pwsh
        run: |
          $out = "artifacts"
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          Copy-Item -Recurse -Force "SlideSCI\bin\Release\*" $out
          Compress-Archive -Path $out\* -DestinationPath "SlideSCI_Release.zip" -Force

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SlideSCI_Release
          path: |
            artifacts/**
            SlideSCI_Release.zip
